[build]
  publish = "dist"
  command = "npm run build"

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables
[build.environment]
  NODE_VERSION = "18"
